config/routes.rb
Rails.application.routes.draw do
  get '/user/:id', to: 'home#user_page', as: :user_id
  get '/gossip/:id', to: 'home#gossip_show', as: :gossip_id
  get '/home', to: 'home#home_page'
  get '/welcome/:first_name', to: 'home#landing_page'
  get '/contact', to: 'home#contact_show'
  get '/team', to: 'home#show_team'

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :likes, :as => :likeable, dependent: :destroy
  has_many :comments, :as => :commentable, dependent: :destroy
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :comments, :as => :commentable, dependent: :destroy
  has_many :join_table_gossip_tags 
  has_many :tags, through: :join_table_gossip_tags
  has_many :likes, :as => :likeable, dependent: :destroy
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/join_table_message_recipient.rb
class JoinTableMessageRecipient < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :private_message
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_table_message_recipients
  has_many :recipients, class_name: "User", through: :join_table_message_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :join_table_message_recipients
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "JoinTableMessageRecipient"
  has_many :likes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home_page
    @gossips = Gossip.all
  end

  def gossip_show
    @gossip = Gossip.find(params[:id])
  end

  def landing_page
    @first_name = params[:first_name]
  end

  def user_page
    @user = User.find(params[:id])
  end

  def contact_show
  end

  def show_team
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/contact_show.html.erb
<html>
    <body>
    <div class="jumbotron contact">
        </div>
        <section class="dark-wrapper opaqued parallax" data-parallax="scroll" data-speed="0.7">
            <div class="section-inner pad-top-200">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 mt30 wow text-center animated" style="visibility: visible;">
                            <h2 class="section-heading">Contact Us</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section id="welcome">
            <div class="section-inner nopaddingbottom">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <p class="lead">La team Thyme est continuellement en phase d'amélioration, nous sommes donc friands de commentaires et de retours.</p>
                            <p class="mt30"><span class="btn btn-primary btn-theme page-scroll"><%= link_to "Voir la Team", team_path %></span></p>
                        </div>

                        <div class="col-md-6">
                            <div id="message"></div>
                            <form method="get" action="/home" id="contactform" class="main-contact-form wow animated" style="visibility: visible;">
                                <input type="text" class="form-control col-md-4" name="name" placeholder="Your Name *" id="name" required="" data-validation-required-message="Please enter your name.">
                                <input type="text" class="form-control col-md-4" name="email" placeholder="Your Email *" id="email" required="" data-validation-required-message="Please enter your email address.">
                                <textarea name="comments" class="form-control" id="comments" placeholder="Your Message *" required="" data-validation-required-message="Please enter a message."></textarea>
                                <input class="btn btn-primary mt30 btn-white pull-right" type="submit" name="submit" value="Submit">
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </section>
    </body>
</html>

app/views/home/gossip_show.html.erb
<html>
  <head>
    <title>Potin n°<%= @gossip.id %></title>
  </head>
  <body>
      <!--POTIN -->
    <div class="container">
      <h1>PAGE POTIN</p>
      <h2>Voici la page du potin n°<%=@gossip.id %></h2>
      <div class="bd-example">
        <dl>
            <dt>Son auteur</dt>
                <dd><%= link_to "#{@gossip.user.first_name}", user_id_path(@gossip.user.id) %> </dd>
            <dt>Contenu du potin</dt>
                <dd><%= @gossip.content%></dd>
            <dt>Date de création</dt> 
                <dd><%= @gossip.created_at%></dd>
        </dl>
      </div>
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Commentaires</th> 
            <th scope="col">Auteur</th> 
          </tr>
        </thead>

        <tbody>
          <% @gossip.comments.each do |comment| %>
            <tr>
              <td><%= comment.content %></td>
              <td><%= link_to "#{comment.user.first_name}", user_id_path(comment.user.id) %></td>
            </tr> 
          <% end %>
        </tbody>
      </table>
    </div>
  </body>
</html>

app/views/home/home_page.html.erb
<html>
    <body>
        <div class="container">
            <div class="row">
                <% @gossips.each do |gossip| %>
                    <div class="col-lg-3 col-md-6 col-xs-12 between_cards">
                        <div class="box-part text-center cards-gossip">
                            <div class="card text-white bg-dark">
                                <div class="card-body card-home">
                                    <h5 class="card-title"><%= gossip.title %></h5>
                                    <h6 class="card-subtitle mb-2 text-muted">Auteur : <%= link_to "#{gossip.user.first_name}", user_id_path(gossip.user.id) %> </h6>
                                    <p class="card-text"><%= gossip.comments.length %> commentaires</p>
                                    <div class='btn btn-primary'><%= link_to "Le potin", gossip_id_path(gossip.id) %></div>
                                </div>
                            </div>
                        </div>
                    </div>
                <% end %>	
            </div>		
        </div>
    </body>
</html>

app/views/home/landing_page.html.erb
<html>

    <body>
        <div class="jumbotron gossip">
            <h1 class="display-4">Welcome <%= @first_name %>!<br>Ici c'est notre super site de potins, chouette non ?</h1>
            <hr class="my-4">
        </div>

    </body>
</html>

app/views/home/show_team.html.erb
<html>
    <body>
        <div class="card">
            <h5 class="card-header">Team Thyme</h5>
            <div class="card-body">
                <h5 class="card-title">The Gossip Project</h5>
                <p class="card-text">made by Fred, helped by Team Thyme.</p>
            </div>
        </div>
    </body>
</html>

app/views/home/user_page.html.erb
<html>
    <head>
        <title>Page Auteur</title>
    </head>
    <body>
        <!--AUTEUR-->
                <%= @user.first_name%> <%= @user.last_name%>

                <dl>
                    <dt>Age</dt>
                    <dd><%= @user.age%></dd>
                    <dt>Email</dt>
                    <dd><%= @user.email%></dd>
                    <dt>Description</dt>
                    <dd><%= @user.description%></dd>
                    <dt>Ville</dt>
                    <dd><%= @user.city.name%></dd>
               </dl> 
           
            <tr>
                <th scope="col">Id</th> 
                <th scope="col">Gossips</th>
                <th scope="col">Lien</th> 
            </tr>
            <% @user.gossips.each do |gossip| %>
                <tr>
                <td><%= gossip.id %></td>
                <td><%=gossip.content %></td>
                <td><%= link_to "Gossip", gossip_id_path(gossip.id) %></td>
                </tr> 
            <% end %>
        </table>

    
            <tr>
                <th scope="col">Id</th> 
                <th scope="col">Commentaires</th>
                <th scope="col">Lien gossip</th> 
            </tr>
           
            <% @user.comments.each do |comment| %>
                <tr>
                <td><%= comment.id %></td>
                <td><%= comment.content %></td>
                <% commentable = comment
                gossip = commentable.commentable_type
                while gossip != 'Gossip'
                    commentable = Comment.all.find(commentable.commentable_id)
                    gossip = commentable.commentable_type
                end 
                %>
                <td><%= link_to "#{gossip}", gossip_id_path(commentable.commentable_id) %></td>
                </tr> 
            <% end %>
         
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <!-- NAVBAR -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="navbar-brand"><%= link_to "The Gossip Project", home_path %></div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <div class="nav-link"><%= link_to "Home", home_path %></div>
                </li>
                <li class="nav-item">
                    <div class="nav-link"><%= link_to "Contact", contact_path %></div>
                </li>
                <li class="nav-item">
                    <div class="nav-link"><%= link_to "Team", team_path %></div>
                </li>
                </ul>
            </div>
        </nav>
        <%= yield %>
                <footer>
                    <p>© Fred 2019</p>
                </footer>
  </body>
</html>